sudo: false
language: php
dist: trusty

php:
  - 7.1

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

install: travis_retry composer update --prefer-dist

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/lib/
